apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: ${{ values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          resources:
            limits:
              memory: ${{ values.memory }}
          ports:
            - containerPort: 8080
